(defun your-config-name-here ()
  (interactive)
  (color-theme-install
   '(your-config-name-here
      ((background-color . "#000000")
      (background-mode . light)
      (border-color . "#ff1a1a")
      (cursor-color . "#00f512")
      (foreground-color . "#eeeeec")
      (mouse-color . "black"))
     (fringe ((t (:background "#ff1a1a"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#7e1fea"))))
     (region ((t (:background "#0b02e8"))))
     (font-lock-builtin-face ((t (:foreground "#d90d0f"))))
     (font-lock-comment-face ((t (:foreground "#b36100"))))
     (font-lock-function-name-face ((t (:foreground "#0af511"))))
     (font-lock-keyword-face ((t (:foreground "#c21978"))))
     (font-lock-string-face ((t (:foreground "#001df5"))))
     (font-lock-type-face ((t (:foreground"#ec5209"))))
     (font-lock-constant-face ((t (:foreground "#bb4935"))))
     (font-lock-variable-name-face ((t (:foreground "#925476"))))
     (minibuffer-prompt ((t (:foreground "#e8f5f8" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'your-config-name-here)


(defun color-theme-euphoria ()
  "Color theme by oGLOWo, created 2000-04-19.
Green on black theme including font-lock, speedbar, and widget."
  (interactive)
  (color-theme-install
   '(color-theme-euphoria
     ((background-color . "gray15")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "yellow")
      (foreground-color . "limegreen")
      (mouse-color . "yellow"))
     ((help-highlight-face . underline)
      (list-matching-lines-face . bold)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "misc-fixed"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (cursor ((t (:background "yellow"))))
     (fixed-pitch ((t (:family "courier"))))
     (font-lock-builtin-face ((t (:foreground "magenta"))))
     (font-lock-comment-face ((t (:foreground "deeppink"))))
     (font-lock-constant-face ((t (:foreground "blue"))))
     (font-lock-doc-face ((t (:foreground "cyan"))))
     (font-lock-doc-string-face ((t (:foreground "cyan"))))
     (font-lock-function-name-face ((t (:foreground "purple"))))
     (font-lock-keyword-face ((t (:foreground "red"))))
     (font-lock-preprocessor-face ((t (:foreground "blue1"))))
     (font-lock-reference-face ((t (nil))))
     (font-lock-string-face ((t (:foreground "cyan"))))
     (font-lock-type-face ((t (:foreground "yellow"))))
     (font-lock-variable-name-face ((t (:foreground "violet"))))
     (font-lock-warning-face ((t (:bold t :foreground "red" :weight bold))))
     (fringe ((t (:background "gray16" :foreground "#00ff00"))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey20" :foreground "grey90" :box nil))))
     (highlight ((t (:background "darkolivegreen"))))
     (horizontal-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-lazy-highlight-face ((t (:background "paleturquoise4"))))
     (italic ((t (:italic t :slant italic))))
     (menu ((t (:background "gray16" :foreground "green"))))
     (modeline ((t (:background "gray16" :foreground "#00ff00" :box (:line-width -1 :style released-button)))))
     (modeline-buffer-id ((t (:background "gray16" :foreground "#00ff00"))))
     (modeline-mousable ((t (:background "gray16" :foreground "#00ff00"))))
     (modeline-mousable-minor-mode ((t (:background "gray16" :foreground "#00ff00"))))
     (mouse ((t (:background "yellow"))))
     (primary-selection ((t (:background "#00ff00" :foreground "black"))))
     (region ((t (:background "steelblue" :foreground "white"))))
     (scroll-bar ((t (:background "gray16" :foreground "#00ff00"))))
     (secondary-selection ((t (:background "#00ff00" :foreground "black"))))
     (show-paren-match-face ((t (:background "turquoise"))))
     (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "#00ff00"))))
     (speedbar-directory-face ((t (:foreground "#00ff00"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "#00ff00" :foreground "purple"))))
     (speedbar-selected-face ((t (:foreground "deeppink" :underline t))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (tool-bar ((t (:background "gray16" :foreground "green" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "gray16" :foreground "#00ff00"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vertical-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (widget-button-face ((t (:bold t :weight bold))))
     (widget-button-pressed-face ((t (:foreground "red"))))
     (widget-documentation-face ((t (:foreground "lime green"))))
     (widget-field-face ((t (:background "dim gray"))))
     (widget-inactive-face ((t (:foreground "light gray"))))
     (widget-single-line-field-face ((t (:background "dim gray"))))
     (zmacs-region ((t (:background "steelblue" :foreground "white")))))))

